Remove vscode-nls
It is causing the extension to fail to activate:
```
[error] Activating extension mesonbuild.mesonbuild failed due to an error:
[error] Error: Cannot find module 'vscode-nls'
```

There seems to be a new mechanism with vscode-l10n but since we were not
doing translations anyway, let's drop it for now.